name: 'rust-audit-check'
description: 'Run cargo audit and check for security advisories'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  token:
    description: GitHub Actions token
    required: true
  ignore:
    description: Comma-separated list of advisory ids to ignore
    required: false
  file:
    description: The path to the Cargo.lock file to scan.
    required: false
    default: Cargo.lock

runs:
  using: 'node16'
  main: 'dist/index.js'
